name = "Snappy"
uuid = "59d4ed8c-697a-5b28-a4c7-fe95c22820f9"
license = "MIT"
desc = "Julia wrapper of the Snappy compression format"
version = "0.4.0"

[deps]
snappy_jll = "fe1e1685-f7be-5f59-ac9f-4ca204017dfd"

[compat]
julia = "1"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random"]
